//
//  MeetTheDevView.swift
//  RantingApp
//
//  Created by Aaron McKain on 5/28/23.
//

import SwiftUI

struct WelcomeView: View {
    var body: some View {
        VStack{
            Text("Welcome to...")
                .font(.title)
                .fontWeight(.ultraLight)
                .padding(.top, 20.0)
            HStack{
                Text("Nothin' Butta \nThang")
                    .font(.largeTitle)
                    .fontWeight(.bold)
                    .padding([.top, .leading, .bottom], 15.0)
                    .foregroundColor(Color.white)
                Spacer()
            }
            .frame(width: UIScreen.main.bounds.width * 0.96, height: UIScreen.main.bounds.height * 0.15)
            .background(Color(red: 99/255, green: 56/255, blue: 174/255))
            .cornerRadius(20)
            
            VStack{
                Text("Enter a rant session whenever you feel upset!")
                    .font(.title3)
                    .multilineTextAlignment(.center)
                    .padding(.vertical)
                
                Text("Read some articles on mental health!")
                    .font(.title3)
                    .multilineTextAlignment(.center)
                    .padding(.vertical)

                Text("Set a couple self care reminders!")
                    .font(.title3)
                    .multilineTextAlignment(.center)
                    .padding(.vertical)
                Text("Review a personalized weekly report generated by AI!")
                    .font(.title3)
                    .multilineTextAlignment(.center)
                    .padding(.vertical)

            }
            
            Spacer()
        }
    }
}

struct WelcomeView_Previews: PreviewProvider {
    static var previews: some View {
        WelcomeView()
    }
}
